services:
  - type: web
    name: dr-phone-backend
    env: node
    buildCommand: npm install
    startCommand: node src/app.js
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080 