services:
  - type: web
    name: dr-phone-backend
    env: node
    buildCommand: npm install
    startCommand: node app.js
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
      filesystem: ext4
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000 